### ISSUE TITLE
Klipper on MK3S

### ISSUE THREAD

**Issue by brotherdust** [PrusaOwners/prusaowners#65]
I followed the guide to getting Klipper set up on MK3S, but ran into an issue on the firmware flash step. The printer gets stuck on "updating... do not disconnect". The flash utility indicates that the flash was successful.

Rebooted the printer and it's just stuck at the boot screen now (Prusa i3...). Any thoughts?

**Comment by Arksine** [comment]
Most likely its an issue with the configuration, there have been some config breaking changes recently and I haven't had a chance to update the sample configuration.  If you check /tmp/klippy.log it will tell you what is wrong.

**Comment by brotherdust** [comment]
Here's the result of the flashing process:
```
pi@octopi:~/klipper $ make flash FLASH_DEVICE=/dev/serial/by-id/usb-Prusa_Research__prusa3d.com__Original_Prusa_i3_MK3_-if00
  Flashing out/klipper.elf.hex to /dev/serial/by-id/usb-Prusa_Research__prusa3d.com__Original_Prusa_i3_MK3_-if00 via avrdude

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e9801 (probably m2560)
avrdude: reading input file "out/klipper.elf.hex"
avrdude: writing flash (23720 bytes):

Writing | ################################################## | 100% 4.19s

avrdude: 23720 bytes of flash written
avrdude: verifying flash memory against out/klipper.elf.hex:
avrdude: load data flash data from input file out/klipper.elf.hex:
avrdude: input file out/klipper.elf.hex contains 23720 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 3.05s

avrdude: verifying ...
avrdude: 23720 bytes of flash verified

avrdude: safemode: Fuses OK (E:FD, H:D0, L:FF)

avrdude done.  Thank you.
```


Here's the output from `/tmp/klippy.log`:
```
cat /tmp/klippy.log
Starting Klippy...
Args: ['/home/pi/klipper/klippy/klippy.py', '/home/pi/printer.cfg', '-l', '/tmp/klippy.log']
Git version: 'v0.6.0-1892-g5aa5b0f4'
CPU: 4 core ARMv7 Processor rev 4 (v7l)
Python: '2.7.13 (default, Sep 26 2018, 18:42:22) \n[GCC 6.3.0 20170516]'
Start printer at Tue Dec  3 12:36:45 2019 (1575401805.1 9.4)
===== Config file =====
[probe]
pin = PB4
x_offset = 24
y_offset = 5
z_offset = 0
speed = 10.0

[bed_mesh]
speed = 100
min_point = 11,1
max_point = 215,193
probe_count = 3,3
mesh_pps = 2,2
algorithm = lagrange

[homing_override]
gcode =
        G1 Z3
        G28 X0 Y0
        G1 X101 Y100 F5000
        G28 Z0
axes = Z
set_position_x = 0
set_position_y = 0
set_position_z = 0

[gcode_macro G80]
gcode =
        G28
        BED_MESH_CALIBRATE
        G1 X0 Y0 Z0.4 F4000

[gcode_macro G81]
gcode =
        BED_MESH_OUTPUT

[stepper_x]
step_pin = PC0
dir_pin = !PL0
enable_pin = !PA7
step_distance = .01
endstop_pin = tmc2130_stepper_x:virtual_endstop
position_endstop = 0
position_max = 250
homing_speed = 50
homing_retract_dist = 0

[tmc2130 stepper_x]
cs_pin = PG0
microsteps = 16
interpolate = True
run_current = .281738
hold_current = .281738
homing_current = .149155
sense_resistor = 0.220
diag1_pin = !PK2
driver_iholddelay = 8
driver_tpowerdown = 0
driver_tbl = 2
driver_toff = 3
driver_hend = 1
driver_hstrt = 5
driver_pwm_freq = 2
driver_pwm_grad = 2
driver_pwm_ampl = 230
driver_pwm_autoscale = True
driver_sgt = 3

[stepper_y]
step_pin = PC1
dir_pin = PL1
enable_pin = !PA6
step_distance = .01
endstop_pin = tmc2130_stepper_y:virtual_endstop
position_endstop = -4
position_max = 210
position_min = -4
homing_speed = 50
homing_retract_dist = 0

[tmc2130 stepper_y]
cs_pin = PG2
microsteps = 16
interpolate = True
run_current = .3480291
hold_current = .3480291
homing_current = .182301
sense_resistor = 0.220
diag1_pin = !PK7
driver_iholddelay = 8
driver_tpowerdown = 0
driver_tbl = 2
driver_toff = 3
driver_hend = 1
driver_hstrt = 5
driver_pwm_freq = 2
driver_pwm_grad = 2
driver_pwm_ampl = 235
driver_pwm_autoscale = True
driver_sgt = 3

[stepper_z]
step_pin = PC2
dir_pin = !PL2
enable_pin = !PA5
step_distance = .0025
endstop_pin = probe:z_virtual_endstop
position_max = 200
position_min = -2
homing_speed = 13.333

[tmc2130 stepper_z]
cs_pin = PK5
microsteps = 16
interpolate = True
run_current = .53033
hold_current = .53033
homing_current = .348029
sense_resistor = 0.220
diag1_pin = !PK6
driver_iholddelay = 8
driver_tpowerdown = 0
driver_tbl = 2
driver_toff = 3
driver_hend = 1
driver_hstrt = 5
driver_pwm_freq = 2
driver_pwm_grad = 4
driver_pwm_ampl = 200
driver_pwm_autoscale = True
driver_sgt = 4

[extruder]
step_pin = PC3
dir_pin = PL6
enable_pin = !PA4
step_distance = .0035714
nozzle_diameter = 0.400
filament_diameter = 1.750
max_extrude_cross_section = 50.0
max_extrude_only_distance = 500.0
max_extrude_only_velocity = 120.0
max_extrude_only_accel = 1250.0
heater_pin = PE5
sensor_type = ATC Semitec 104GT-2
sensor_pin = PF0
control = pid
pid_kp = 16.13
pid_ki = 1.1625
pid_kd = 56.23
min_temp = 0
max_temp = 305

[tmc2130 extruder]
cs_pin = PK4
microsteps = 32
interpolate = True
run_current = .513757
hold_current = .513757
homing_current = .314883
sense_resistor = 0.220
diag1_pin = !PK3
driver_iholddelay = 8
driver_tpowerdown = 0
driver_tbl = 2
driver_toff = 3
driver_hend = 1
driver_hstrt = 5
driver_pwm_freq = 2
driver_pwm_grad = 4
driver_pwm_ampl = 240
driver_pwm_autoscale = True
driver_sgt = 3

[heater_bed]
heater_pin = PG5
sensor_type = EPCOS 100K B57560G104F
sensor_pin = PF2
control = pid
pid_kp = 126.13
pid_ki = 4.3
pid_kd = 924.76
min_temp = 0
max_temp = 125

[heater_fan nozzle_cooling_fan]
pin = PH5
heater = extruder
heater_temp = 50.0
fan_speed = 1.0

[fan]
pin = PH3

[mcu]
serial = /dev/serial/by-id/usb-Prusa_Research__prusa3d.com__Original_Prusa_i3_MK3_-if00

[display]
lcd_type = hd44780
rs_pin = PD5
e_pin = PF7
d4_pin = PF5
d5_pin = PG4
d6_pin = PH7
d7_pin = PG3
encoder_pins = ^PJ1,^PJ2
click_pin = ^!PH6

[printer]
kinematics = cartesian
max_velocity = 300
max_accel = 1500
max_z_velocity = 10
max_z_accel = 200

[static_digital_output debug_led]
pins = !PB7

[output_pin BEEPER_pin]
pin = PH2
pwm = True
value = 0
shutdown_value = 0
cycle_time = 0.001
scale = 1000

[gcode_macro M300]
default_parameter_s = 1000
default_parameter_p = 100
gcode =
        SET_PIN PIN=BEEPER_pin VALUE={S}
        G4 P{P}
        SET_PIN PIN=BEEPER_pin VALUE=0

[menu __filament __load]
type = command
name = Load Filament
gcode =
        LOAD_FILAMENT

[menu __filament __unload]
type = command
name = Unload Filament
gcode =
        UNLOAD_FILAMENT

[menu __filament __feed]
type = input
name = Feed Filament: {0:.1f}
parameter = 0
input_step = 1
gcode =
        M83
        G1 E{0:.1f} F400

[prusa_gcodes]
=======================
bed_mesh: generated points
0: (11.0, 1.0)
1: (113.0, 1.0)
2: (215.0, 1.0)
3: (215.0, 97.0)
4: (113.0, 97.0)
5: (11.0, 97.0)
6: (11.0, 193.0)
7: (113.0, 193.0)
8: (215.0, 193.0)
Declaration of '__filament __load' hides previous menuitem declaration
Declaration of '__filament __unload' hides previous menuitem declaration
Declaration of '__filament __feed' hides previous menuitem declaration
Extruder max_extrude_ratio=20.787584
Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 138, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 135, in _read_config
    pconfig.check_unused_options(config)
  File "/home/pi/klipper/klippy/configfile.py", line 260, in check_unused_options
    section,))
Error: Section 'prusa_gcodes' is not a valid config section
```

Here's the result on the printer screen:
![IMG_0221](https://user-images.githubusercontent.com/10413016/70096106-84eb6400-15e3-11ea-99be-0b36e5f2108d.jpeg)

Hopefully that helps?

**Comment by brotherdust** [comment]
Update: taking the `[prusa_gcodes]` section out of the printer.cfg fixed it. =)
